services:
  # MongoDB service with replica set for Prisma transactions
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: stockly-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: stockly
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - stockly-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockly-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/stockly?authSource=admin&directConnection=true&retryWrites=true&w=majority
      - JWT_SECRET=your-super-secret-jwt-key-for-development-only
      - JWT_EXPIRES_IN=24h
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - stockly-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  stockly-network:
    driver: bridge